### ISSUE TITLE
Remote I/O error - running example.py

### ISSUE THREAD

**Issue by crossett** [bluerobotics/ms5837-python#16]
Hi,

I am trying to run example.py on a RPi4, but when I do, I get the following error:

```
Traceback (most recent call last):
  File "./example.py", line 13, in <module>
    if not sensor.init():
  File "/home/pi/ms5837-python/ms5837/ms5837.py", line 74, in init
    self._bus.write_byte(self._MS5837_ADDR, self._MS5837_RESET)
IOError: [Errno 121] Remote I/O error
```

It appears that the ms5837 is recognized when I run `i2cdetect`:

```
i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --
```

Any ideas why I'm getting this error?  Any help would be greatly appreciated!

Thanks,
Jonathan

**Comment by msp4096** [comment]
I am seeing the same exact error on my RPi4 setup.  I sometimes don't see the device when doing i2cdetect as well.  Is this an issue with the library?  Or could this be a raspberry pi issue?

**Comment by akash-aeronuts** [comment]
Has there been any solution for this as I'm also facing the same issues

**Comment by akash-aeronuts** [comment]
@msp4096 @crossett have you resolved your problems or could you share any insights on the problem

**Comment by steven102814** [comment]
Having a similar issue while using Jetson Orin Nano any fix? I can test on a Raspberry Pi 4 if necessary but my main computer to use this sensor with for was expected to be the Nano.

**Comment by HJGrant** [comment]
I have the same issue on Jetson Orin AGX DevKit
